# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.9
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 163.0
    max_position: 6.2832
    min_position: -6.2832
    max_velocity: 2.618
    max_acceleration: 1.5708

  joint_2:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 163.0
    max_position: 6.2832
    min_position: -6.2832
    max_velocity: 2.618
    max_acceleration: 1.5708

  joint_3:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 96.0
    max_position: 2.618
    min_position: -2.618
    max_velocity: 3.1416
    max_acceleration: 1.5708
    
  joint_4:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 50.0
    max_position: 6.2832
    min_position: -6.2832
    max_velocity: 3.927
    max_acceleration: 1.5708

  joint_5:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 50.0
    max_position: 6.2832
    min_position: -6.2832
    max_velocity: 3.927
    max_acceleration: 1.5708

  joint_6:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 50.0
    max_position: 6.2832
    min_position: -6.2832
    max_velocity: 3.927
    max_acceleration: 1.5708

  tool0-hand:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 50.0
    max_position: 6.2832
    min_position: -6.2832
    max_velocity: 3.927
    max_acceleration: 1.5708